[package]
name = "nidhogg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp-serde = "1.1.1"
serde = { version = "1.0.150", features = ["derive"] }
thiserror = "1.0.38"
tracing = "0.1.37"
nidhogg_derive = { workspace = true }

[dev-dependencies]
color-eyre = "0.6.2"
tracing-subscriber = "0.3.16"