name: check, test, lints and build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cicd:
    uses: IntelligentRoboticsLab/bondi/blob/main/.github/workflows/rust.yml@main
